dataset:
  train_file: ../Datasets/LitCovid/BC7-LitCovid-Train.csv
  val_file: ../Datasets/LitCovid/BC7-LitCovid-Dev.csv
  topics: ../Datasets/LitCovid/topics.json
parameters:
  n_labels: 7
  lr: 0.002
  epochs: 30
  batch_size: 2
  max_length: 512
  dropout: 0.1
  threshold: 0.5
pretrained_model: bionlp/bluebert_pubmed_uncased_L-12_H-768_A-12