dataset:
  train_file: Datasets/cei/train.json
  val_file: Datasets/cei/val.json
  topics: Datasets/cei/topics.json
parameters:
  n_labels: 11
  lr: 0.00002
  epochs: 30
  batch_size: 4
  max_length: 512
  dropout: 0.1
  threshold: 0.5
  token_classification: False
pretrained_model: bionlp/bluebert_pubmed_uncased_L-12_H-768_A-12
logging:
  project: ncbi_bert_pubmed
  logger_file: cei
checkpoint:
  folder: cei_models
  subfolder: cei_ncbi_bert_pubmed