dataset:
  train_file: Datasets/HoC/train.json
  val_file: Datasets/HoC/val.json
  test_file: Datasets/HoC/test.json
  topics: Datasets/HoC/topics.json
parameters:
  n_labels: 10
  lr: 0.00002
  epochs: 30
  batch_size: 4
  max_length: 512
  dropout: 0.1
  threshold: 0.5
  token_classification: False
pretrained_model: bionlp/bluebert_pubmed_uncased_L-12_H-768_A-12
logging:
  project: ncbi_bert_pubmed
  logger_file: HoC
checkpoint:
  folder: HoC_models
  subfolder: HoC_ncbi_bert_pubmed